### ISSUE TITLE
Maven Central Releases of json-java

### ISSUE THREAD

**Issue by BGehrels** [douglascrockford/JSON-java#149]
I maintained (and am somehow still maintaining) the Maven Central build
for org.json:json. I had to "swear to keep it up to date" when i first
asked Douglas if he would be okay with me uploading it as a third party
artifact.

As i saw the maintainer change, i wanted to ask what your plans
regarding the build and release process are? I have seen, that you are
building a test harness right now? I guess the easiest way would be to
have all the tests and sources together in one project, making sure that
only stable and tested code gets released (and giving you as the project
maintainer the decision if and when to release).

Otherwise i would just continue to publish releases, whenever my montly
calender reminder rings and new code changes exist :-)

Best regards,
Benjamin

**Comment by stleary** [comment]
Hi Benjamin,
Thank you for reaching out, will get back to you soon.
Best regards, Sean

**Comment by kushieda-minori** [comment]
@BGehrels see also #125 and the discussion in https://github.com/douglascrockford/JSON-java/pull/143#issuecomment-127808512 if you haven't already

**Comment by johnjaylward** [comment]
@BGehrels see also #125 and the discussion in https://github.com/douglascrockford/JSON-java/pull/143#issuecomment-127808512 if you haven't already

**Comment by stleary** [comment]
We would like to keep the Maven central repository up to date with JSON-java releases. The details of the proposed process are up for discussion. For example,
* Should Maven releases be every month or so, or driven by pushes to the JSON-java project?
* Should every JSON-java GitHub push result in a new Maven release? 
* Should JSON-java start tagging releases, to indicate the need for a Maven release and to facilitate mapping between GitHub project and Maven?
* Should the unit test project be included in the Maven release?
* Should the source code be modified to support Maven? (The answer will be "no" for JSON-java, but possible for JSON-Java-unit-test)


If you would like to be part of the effort going forward, please let me know.

**Comment by johnjaylward** [comment]
If we go with merging the tests into the main source, we could use gradle as the build tool to handle running the tests and also use the built in CI support in github. Gradle is nicely configurable and can reside with the source with no changes to the current project layout/source. 

However if we do merge the tests, it may make more sense to update the layout at least a little too accommodate them. At that point, it may be easier to just use the standard maven layout of src/main and src/test

**Comment by stleary** [comment]
* Any changes to JSON-Java-Unit-Tests to support Maven and/or Gradle build compatibility are welcome. Just make a pull request; I will accept it so long as it still builds. 
* The JSON-java Maven central repository can also, I think, have any structure or additional files that we deem appropriate. 
* JSON-java remains off limits for directory moves or build files at the present time.

Will this work for everyone?

**Comment by johnjaylward** [comment]
I'm unsure how "The JSON-java Maven central repository" and the main "JSON-java" repository would be kept separate. Do you propose a new project that uses git's submodule options in the "JSON-java Maven central repository" to pull in both "JSON-Java-Unit-Tests" and "JSON-java" ?

**Comment by stleary** [comment]
Sorry, my misunderstanding. Based on the Sonatype docs for deploying to the Maven central repository, I had assumed that source code was required. However, looking at the latest JSON-java release, that is not the case. If we don't deploy source, then we won't deploy unit tests, either.

**Comment by stleary** [comment]
Hopefully we are all on the same page now. @BGehrels, if you are still ready to proceed, I have added a JSON-java tag and release: https://github.com/douglascrockford/JSON-java/releases/tag/20150729. The tagname matches the date of the most recent commit to the JSON-java master branch.

This tag should be used for the next Maven central repository update.  The Maven release should have the same name as the tag: 20150729. The release artifact should be a jar file compiled with JDK  v1.8, and whose contents and META-INF data are like the artifact in http://mvnrepository.com/artifact/org.json/json/20141113, except with the latest compiled JSON-java class files. 

Please let me know if there are any questions or concerns about the JSON-java tag or release information, or the proposed Maven target file.

**Comment by stleary** [comment]
@BGehrels, please let me know if you would like to proceed with the next Maven central repository release.

**Comment by BGehrels** [comment]
The release has been built, and deployed to maven central. It may take some hours to become visible there...

**Comment by stleary** [comment]
I found the release here: http://central.maven.org/maven2/org/codeartisans/org.json/20150729/org.json-20150729.jar

The unit test code does not build with the released jar. I suspect the jar may be lacking any of the recent code changes. Also, it still has a zip directory,which no longer exists. Minor point, the release is showing the MIT license. This needs to be changed to the org.json license: http://www.json.org/license.html. Can you address these problems as soon as possible? In the future, we need to work through these and all other potential issues prior to releasing the code.

**Comment by BGehrels** [comment]
You are right, this one has a lot of problems. But it is not the one i deployed :-) The one you looked at is org.codeartisans:org.json:20150729. It has probably been built by the owner of the domain codeartisans.org.

The one i have built is deployed as org.json:json:20150729 and can be found here:
https://search.maven.org/#artifactdetails|org.json|json|20150729|jar

**Comment by stleary** [comment]
Oops, my error, thanks for clarifying. Although there is still a problem with the unit tests, it is on the test side - somehow I got out of sync and committed a test that is not supported on the JSON-java master branch. I will fix this on the test side today. The Maven release looks great, nice work, and thanks!

**Comment by stleary** [comment]
Maven release for JSON-java release 20150729: 
groupId: org.json
artifactId: json
version: 20150729
packaging: jar
location: https://search.maven.org/#artifactdetails|org.json|json|20150729|jar
